---
- name: Check if Docker is installed
  ansible.builtin.command: docker --version
  register: docker_check
  changed_when: false
  failed_when: false

- name: Build Docker documentation image
  ansible.builtin.command:
    cmd: "docker build -t {{ docker_image_name }} ."
    chdir: "{{ repo_root }}"
  when: docker_check.rc == 0
  changed_when: true
